-- GENERATED by scripts/build-mailer-seed.mjs from docs/email-campaigns/*.md.
-- Adds missing templates only; never overwrites edits made in /admin/mailer.

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$a-1$tpl$, $tpl$A · Email 1 — Introduction / authenticity$tpl$, $tpl$A$tpl$, 1,
  $tpl$An authentic Our Lady of Guadalupe canvas for @parishname$tpl$,
  $tpl$24×36 rolled canvas, image from the 1998-certified digital archive of the Sacred Original, printed in the USA. Two Mexican certificates. $114 with free shipping.$tpl$,
  $tpl$Dear @firstname,

I'm writing because @parishname in @city, @state is dedicated to Our Lady of Guadalupe, and I wanted you to know about something that may be useful for your parish or ministry.

Primos Maternos offers a 24" × 36" rolled canvas reproduction of the tilma of Saint Juan Diego. The image comes from a digital archive of the Sacred Original, which Cardinal Norberto Rivera Carrera, Archbishop Primate of Mexico, certified on December 12, 1998 as a faithful reproduction. The canvas is printed in the USA on archival stock at 287.5 pixels per inch, with nothing enlarged to fill it. Both Mexican certifications come with every order, and both are published in full at [primosmaternos.com/authenticity](https://primosmaternos.com/authenticity) so you can read them before you decide.

**$114 per canvas. Free shipping to the 50 U.S. states and Puerto Rico.**

The timing may also matter to you — Pope Leo XIV has opened a Jubilee Year for Our Lady of Guadalupe, running October 12, 2026 through October 12, 2027, marking 50 years since the tilma was carried into the current New Basilica.

[**Order for @parishname →**](https://primosmaternos.com/parishes?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=a-1)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$a-2$tpl$, $tpl$A · Email 2 — The documents themselves$tpl$, $tpl$A$tpl$, 2,
  $tpl$The documents behind the image, and what they do not say$tpl$,
  $tpl$Cardinal Rivera's 1998 certification and the Virgen Peregrina, both published in full for you to read.$tpl$,
  $tpl$Dear @firstname,

Following up on the canvas I wrote to you about, because the documentation is the part that usually matters to a parish, and it is the part most sellers gesture at without showing.

Two Mexican certifications are preserved with the image.

The first is dated **December 12, 1998** and signed by **Cardinal Norberto Rivera Carrera, Archbishop Primate of Mexico**. It describes the associated print as a *"reproducción fiel del archivo digital del Sagrado Original"* — a **faithful reproduction of the digital archive of the Sacred Original**. The same document identifies **Digital Color, S.A. de C.V.** with the digital capture and reproduction.

The second records that the image known as the **Virgen Peregrina** was **blessed by Pope John Paul II on January 25, 1999**, and traveled throughout Mexico from January 1999 to April 2000 for the Great Jubilee.

Both are published in full, with the Spanish transcribed and translated:

[**Read the certifications →**](https://primosmaternos.com/authenticity?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=a-2)

The same page says what the documents do *not* establish, which I think matters as much. They do not mean that Cardinal Rivera examined any canvas printed since, that any canvas sold today was individually blessed, or that the Church endorses our business. Primos Maternos came under its current ownership in 2005, years after these events, and we present what survives rather than filling the gaps.

Our canvases are printed in the United States and ship rolled, at **$114 with free shipping to the 50 states and Puerto Rico**.

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$a-3$tpl$, $tpl$A · Email 3 — The image itself (value, not sales)$tpl$, $tpl$A$tpl$, 3,
  $tpl$What the Aztecs read in the Guadalupe image$tpl$,
  $tpl$Every fold, sash, and star was a message. A short read for your Guadalupe ministry or December 12 preparation.$tpl$,
  $tpl$Dear @firstname,

Not a sales email — just an article your Guadalupe ministry may find useful for catechesis, a bulletin insert, or December 12 preparation.

Spanish missionaries preached in Mexico for ten years before the tilma with almost no result. In the ten years after Juan Diego opened his cloak in front of the bishop, roughly nine million Aztecs were baptized. Historians of the image now understand why: to the Aztecs the image was a codex, written in symbols they read at a glance.

The mestiza face anticipating a race that didn't yet exist. Hair parted in the middle with no tie — an Aztec sign for a pregnant virgin. The black sash — the Aztec maternity belt. The four-petaled Nahui Ollin over the womb — the Aztec glyph for the presence of God. The stars on her mantle matching the actual sky over Mexico City on the morning of December 12, 1531.

Full breakdown with sources, in about seven minutes of reading:

[**Read: A Codex in the Image →**](https://primosmaternos.com/blog/codex-symbols?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=a-3)

For parishes and ministries that would like the image itself, we make a 24" × 36" rolled canvas — printed in the USA from the same 1998-certified digital archive of the Sacred Original — available for $114, with free U.S. shipping and both Mexican certifications.

[See the image →](https://primosmaternos.com/parishes?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=a-3b)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$a-4$tpl$, $tpl$A · Email 4 — Parish use / final CTA$tpl$, $tpl$A$tpl$, 4,
  $tpl$Ideas for the Guadalupe canvas at @parishname$tpl$,
  $tpl$Shrines, Dec 12 processions, Hispanic ministry, religious education, raffles — six ways parishes have used it.$tpl$,
  $tpl$Dear @firstname,

A last note, then I'll stop.

The 24" × 36" rolled canvas we make has been ordered by parishes for:

- Parish Guadalupe shrines
- December 12 processions and vigil Masses
- Hispanic ministry meeting spaces and offices
- Religious education classrooms
- Rectory and parish office display
- Fundraising raffles for the ministry

With the Jubilee Year opening October 12 and the feast day on December 12, this is a natural year to add the image somewhere in the parish that doesn't have it yet, or refresh what does.

For a parish weighing an image for a church, chapel, school or ministry space, the documentation is there to be examined rather than taken on a claim:

- Cardinal Rivera's **December 12, 1998** certification of the associated print as a faithful reproduction of the digital archive of the Sacred Original
- **Digital Color, S.A. de C.V.** named with the digital capture and reproduction
- The **January 25, 1999** blessing by Pope John Paul II of the image known as the Virgen Peregrina
- Its pilgrimage through Mexico for the Great Jubilee, January 1999 to April 2000

[Read the certifications and the English translations →](https://primosmaternos.com/authenticity?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=a-4b)

**$114 per canvas. Free shipping to the 50 U.S. states and Puerto Rico. Printed in the USA. Both Mexican certifications included. Ships rolled, ready for local framing.**

[**Order for @parishname →**](https://primosmaternos.com/parishes?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=a-4)

Ordering more than one for a diocesan or school initiative? Reply to this email or text me at 732-673-4260 for a bulk quote.

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$b-1$tpl$, $tpl$B · Email 1 — Introduction / authenticity$tpl$, $tpl$B$tpl$, 1,
  $tpl$An authentic Our Lady of Guadalupe canvas for your ministry$tpl$,
  $tpl$24×36 rolled canvas, image from the 1998-certified digital archive of the Sacred Original, printed in the USA. Two Mexican certificates. $114 with free shipping.$tpl$,
  $tpl$Dear @firstname,

I'm writing to the @contactrole at @parishname in @city, @state because your parish's Guadalupe and Hispanic ministry may find this useful.

Primos Maternos offers a 24" × 36" rolled canvas reproduction of the tilma of Saint Juan Diego. The image comes from a digital archive of the Sacred Original, which Cardinal Norberto Rivera Carrera, Archbishop Primate of Mexico, certified on December 12, 1998 as a faithful reproduction. The canvas is printed in the USA on archival stock at 287.5 pixels per inch, with nothing enlarged to fill it. Both Mexican certifications come with every order, and both are published in full at [primosmaternos.com/authenticity](https://primosmaternos.com/authenticity) so you can read them before you decide.

**$114 per canvas. Free shipping to the 50 U.S. states and Puerto Rico.**

The timing is worth noting — Pope Leo XIV has opened a Jubilee Year for Our Lady of Guadalupe, running October 12, 2026 through October 12, 2027, marking 50 years since the tilma was carried into the current New Basilica. A good year to have the image on the ministry wall or in the parish's Guadalupe shrine.

[**See the canvas →**](https://primosmaternos.com/parishes?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=b-1)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$b-2$tpl$, $tpl$B · Email 2 — The image itself (value, not sales)$tpl$, $tpl$B$tpl$, 2,
  $tpl$What the Aztecs read in the Guadalupe image$tpl$,
  $tpl$Every fold, sash, and star was a message. A short read for your ministry or December 12 preparation.$tpl$,
  $tpl$Dear @firstname,

Not a sales email — just an article your Guadalupe ministry may find useful for catechesis, a bulletin insert, or December 12 preparation.

Spanish missionaries preached in Mexico for ten years before the tilma with almost no result. In the ten years after Juan Diego opened his cloak in front of the bishop, roughly nine million Aztecs were baptized. Historians of the image now understand why: to the Aztecs the image was a codex, written in symbols they read at a glance.

The mestiza face anticipating a race that didn't yet exist. Hair parted in the middle with no tie — an Aztec sign for a pregnant virgin. The black sash — the Aztec maternity belt. The four-petaled Nahui Ollin over the womb — the Aztec glyph for the presence of God. The stars on her mantle matching the actual sky over Mexico City on the morning of December 12, 1531.

Full breakdown with sources, about seven minutes of reading:

[**Read: A Codex in the Image →**](https://primosmaternos.com/blog/codex-symbols?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=b-2)

For ministries that would like the image itself, we make a 24" × 36" rolled canvas — printed in the USA from the same 1998-certified digital archive of the Sacred Original — available for $114, with free U.S. shipping and both Mexican certifications.

[See the image →](https://primosmaternos.com/parishes?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=b-2b)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$b-3$tpl$, $tpl$B · Email 3 — Ministry use / final CTA$tpl$, $tpl$B$tpl$, 3,
  $tpl$Ideas for the Guadalupe canvas at @parishname$tpl$,
  $tpl$Shrine, ministry room, Dec 12 procession, religious education, raffle — six ways parishes have used it.$tpl$,
  $tpl$Dear @firstname,

A last note, then I'll stop.

The 24" × 36" rolled canvas we make has been ordered by parish ministries for:

- The parish's Guadalupe shrine
- December 12 processions and vigil Masses
- Hispanic ministry meeting spaces and offices
- Religious education classrooms — especially for December catechesis
- The rectory or parish office
- Fundraising raffles for the ministry

With the Jubilee Year opening October 12 and the feast day on December 12, this is a natural year to add the image somewhere in the parish that doesn't have it yet.

**$114 per canvas. Free shipping to the 50 U.S. states and Puerto Rico. Printed in the USA. Both Mexican certifications included. Ships rolled, ready for local framing.**

[**Order for @parishname →**](https://primosmaternos.com/parishes?utm_source=gmail&utm_medium=email&utm_campaign=parish-outreach-2026&utm_content=b-3)

Ordering more than one? Reply to this email or text me at 732-673-4260 for a bulk quote.

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$c-1$tpl$, $tpl$C · Email 1 — Introduction / authenticity$tpl$, $tpl$C$tpl$, 1,
  $tpl$An authentic Our Lady of Guadalupe canvas for @schoolname$tpl$,
  $tpl$24×36 rolled canvas from the 1998-certified digital archive of the Sacred Original. $114 each, bulk pricing for multiple classrooms.$tpl$,
  $tpl$Dear @firstname,

I'm writing to the @contactrole at @schoolname in @city, @state because the students you teach may find the image of Our Lady of Guadalupe especially meaningful this year.

Primos Maternos offers a 24" × 36" rolled canvas reproduction of the tilma of Saint Juan Diego. The image comes from a digital archive of the Sacred Original, which Cardinal Norberto Rivera Carrera, Archbishop Primate of Mexico, certified on December 12, 1998 as a faithful reproduction. The canvas is printed in the USA on archival stock at 287.5 pixels per inch, with nothing enlarged to fill it. Both Mexican certifications come with every order, and both are published in full at [primosmaternos.com/authenticity](https://primosmaternos.com/authenticity) so you can read them before you decide.

**$114 per canvas. Free shipping to the 50 U.S. states and Puerto Rico. Bulk quotes for multiple classrooms.**

The year is well-timed: Pope Leo XIV has opened a Jubilee Year for Our Lady of Guadalupe (October 12, 2026 through October 12, 2027) marking 50 years since the tilma was transferred into the current New Basilica in Mexico City. It runs through the entire school year and into next.

[**See it for your school →**](https://primosmaternos.com/schools?utm_source=gmail&utm_medium=email&utm_campaign=school-outreach-2026&utm_content=c-1)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$c-2$tpl$, $tpl$C · Email 2 — Curriculum / value$tpl$, $tpl$C$tpl$, 2,
  $tpl$Two Guadalupe resources for your Dec 12 lesson plans$tpl$,
  $tpl$Symbolism the Aztecs read, and the science that cannot explain the tilma. Free reading for religion, history, and Spanish classes.$tpl$,
  $tpl$Dear @firstname,

Not a sales email — two short reads your religion, history, or Spanish teachers may find useful for the Dec 12 unit or Advent programming.

**A Codex in the Image** — what an Aztec saw in the tilma at a glance in 1531. The mestiza face anticipating a race that didn't yet exist. Hair parted and untied (the Aztec sign for a pregnant virgin). The black sash (maternity belt). The four-petaled Nahui Ollin over the womb (the Aztec glyph for the presence of God). The stars on her mantle matching the actual sky over Mexico City on the morning of December 12, 1531. Nine million baptisms in ten years.
[Read →](https://primosmaternos.com/blog/codex-symbols?utm_source=gmail&utm_medium=email&utm_campaign=school-outreach-2026&utm_content=c-2a)

**What Science Cannot Explain About the Tilma** — a cactus-fiber cloak that should have decayed in 20 years, still intact after 495. Nobel chemist Richard Kuhn on the pigments. Callahan and Smith's infrared analysis at NASA. Thirteen human figures found in the pupils of the eyes by a Cornell-trained IBM engineer. Faith-and-science material for high school religion or philosophy.
[Read →](https://primosmaternos.com/blog/tilma-science?utm_source=gmail&utm_medium=email&utm_campaign=school-outreach-2026&utm_content=c-2b)

Both are free to link in your LMS or share in a bulletin.

For schools that would like the image itself in the classroom, we make a 24" × 36" rolled canvas — printed in the USA from the same 1998-certified digital archive of the Sacred Original — for $114 with free U.S. shipping and both Mexican certifications. Bulk pricing for multiple classrooms.

[See it for your school →](https://primosmaternos.com/schools?utm_source=gmail&utm_medium=email&utm_campaign=school-outreach-2026&utm_content=c-2c)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$c-3$tpl$, $tpl$C · Email 3 — School use cases / final CTA$tpl$, $tpl$C$tpl$, 3,
  $tpl$Ideas for the Guadalupe canvas at @schoolname$tpl$,
  $tpl$Classrooms, chapel, hallway, gym, graduation gift — nine places schools have put it, plus how bulk quotes work.$tpl$,
  $tpl$Dear @firstname,

A last note.

The 24" × 36" rolled canvas we make has been ordered by Catholic schools for:

- Religion education classrooms (one per teacher — most common)
- The school chapel or prayer room
- Main hallway or lobby
- Library beside a Marian book display or Latin American history section
- Cafeteria or student commons for December
- Faculty lounge and administrative offices
- Dec 12 processions and school Mass
- Graduation gift or class legacy — framed and installed permanently
- Diocesan bulk orders across multiple schools

**$114 per canvas. Free shipping. Printed in the USA. Both Mexican certifications, published in full on the site. Bulk quotes on request.**

If @schoolname is thinking about outfitting more than one classroom — a typical order is 5 to 15 for a religion department — reply to this email or text me at 732-673-4260 for a bulk quote. Purchase orders accepted.

[**Order for @schoolname →**](https://primosmaternos.com/schools?utm_source=gmail&utm_medium=email&utm_campaign=school-outreach-2026&utm_content=c-3)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$d-1$tpl$, $tpl$D · Email 1 — Introduction / Jubilee opportunity$tpl$, $tpl$D$tpl$, 1,
  $tpl$A Jubilee-year Guadalupe canvas for every parish in the @diocesename$tpl$,
  $tpl$Documented 24×36 tilma reproduction, bulk pricing, PO invoicing. Written quote in one business day.$tpl$,
  $tpl$Dear @firstname,

I'm writing to the @contactrole at the @diocesename because the Guadalupe Jubilee Year Pope Leo XIV opened on October 12 offers a natural occasion for a diocesan-wide initiative.

Primos Maternos produces a 24" × 36" canvas reproduction of the tilma of Saint Juan Diego. The image comes from a digital archive of the Sacred Original, which Cardinal Norberto Rivera Carrera, Archbishop Primate of Mexico, certified on December 12, 1998 as a faithful reproduction. The canvas is printed in the USA on archival stock at 287.5 pixels per inch, with nothing enlarged to fill it. Both Mexican certifications come with every order, and both are published in full at [primosmaternos.com/authenticity](https://primosmaternos.com/authenticity) so you can read them before you decide.

At the diocesan scale — for example, one canvas per parish across the @diocesename's @parishcount parishes — the pricing works out to a per-piece cost well below retail, on a single PO, with either single-address delivery to the chancery or split-shipping to each parish.

Common diocesan uses:

- A Jubilee-year gift to every parish, distributed with a bishop-signed card
- Catholic school system rollout — one canvas per religion classroom
- Hispanic Ministry office distribution at deanery meetings and retreats
- Ordination, installation, and jubilee gifts for clergy

Written quote within one business day of your reply. Purchase orders accepted from established diocesan offices — Net 30 standard.

[**See the diocesan program page →**](https://primosmaternos.com/dioceses?utm_source=gmail&utm_medium=email&utm_campaign=diocesan-outreach-2026&utm_content=d-1)

Or reply to this email with an approximate quantity and target delivery date and I'll return a quote directly.

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$d-2$tpl$, $tpl$D · Email 2 — The image (value, not sales)$tpl$, $tpl$D$tpl$, 2,
  $tpl$What science cannot explain about the tilma — a resource for your office$tpl$,
  $tpl$A summary of the ophthalmology, chemistry, and infrared research on the image — useful for catechesis and Guadalupe-year programming.$tpl$,
  $tpl$Dear @firstname,

Not a sales email — a resource your Hispanic Ministry or Faith Formation office may find useful for Guadalupe-year catechesis, deanery programming, or a bulletin insert.

The 1936 pigment analysis by Nobel chemist Richard Kuhn: not animal, not mineral, not vegetable, no known source. The 1979 infrared analysis by Callahan and Smith: no paint, no brush strokes, no primer, painted in a single step. The thirteen human figures identified in the pupils of the eyes by a Cornell-trained IBM engineer using satellite-imagery algorithms. A NASA scientist's remark that "studying this image has been the most moving experience of my life."

Full write-up, with sources, about eight minutes of reading:

[**Read: What Science Cannot Explain About the Tilma →**](https://primosmaternos.com/blog/tilma-science?utm_source=gmail&utm_medium=email&utm_campaign=diocesan-outreach-2026&utm_content=d-2a)

There is also a companion piece on the Aztec symbolism of the image — the mestiza face, the Nahui Ollin, the winter-solstice constellations on the mantle — which fits the Guadalupe-year theological formation cycle:

[**Read: A Codex in the Image →**](https://primosmaternos.com/blog/codex-symbols?utm_source=gmail&utm_medium=email&utm_campaign=diocesan-outreach-2026&utm_content=d-2b)

Both are free to link in a diocesan newsletter or the Faith Formation LMS.

Diocesan bulk-order details remain here whenever they become relevant:

[Diocesan program →](https://primosmaternos.com/dioceses?utm_source=gmail&utm_medium=email&utm_campaign=diocesan-outreach-2026&utm_content=d-2c)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$d-3$tpl$, $tpl$D · Email 3 — Quote framework / final ask$tpl$, $tpl$D$tpl$, 3,
  $tpl$Six lines to get a diocesan quote from us$tpl$,
  $tpl$Reply with these six items and we'll return written pricing within one business day.$tpl$,
  $tpl$Dear @firstname,

A last note.

If a diocesan-scale Guadalupe canvas program is on the @diocesename's radar at any point in the next 12 months of the Jubilee Year, the fastest way to a quote is a six-line reply to this email:

1. Approximate quantity
2. SKU mix (24"×36" framed, 24"×36" rolled, 36"×54" rolled, 12"×18" gallery wrap)
3. Ship-to (single chancery address, or split-ship to individual parishes)
4. Target delivery date
5. Whether a PO will be issued
6. Whether an initial sample canvas would be useful for internal review before the full order

We return written quotes within one business day. Standard fulfillment window for bulk orders is 3–4 weeks; split-shipping adds 1–2 weeks. Sample canvases can be shipped separately at retail pricing.

The Jubilee Year opened October 12, 2026 and runs through October 12, 2027. Dioceses that want the canvases in parish hands by the December 12 feast should aim for a PO by early November.

[**Diocesan program page →**](https://primosmaternos.com/dioceses?utm_source=gmail&utm_medium=email&utm_campaign=diocesan-outreach-2026&utm_content=d-3)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$holiday-1$tpl$, $tpl$Retail · Email 1 — "Order by November 20 for December 12"$tpl$, $tpl$Retail$tpl$, 1,
  $tpl$Order by Nov 20 for December 12 delivery$tpl$,
  $tpl$The Guadalupe canvas gift guide is up. Framed, rolled, and gallery wrap — from $57.$tpl$,
  $tpl$Dear @firstname,

Two devotional dates are coming up faster than you'd think.

- **December 12** — the feast of Our Lady of Guadalupe
- **December 3–11** — the traditional Novena leading into it

If you're planning to give the tilma canvas as a gift for the feast, or to have it on your own wall for the Novena, order in November. Each canvas is printed and then framed or rolled for that order, which takes five to ten business days before it even reaches the carrier.

- **December 12 feast** — order by **November 20**, or by **November 13** for a rolled canvas you still have to stretch or frame
- **Christmas** — order by **December 4**
- **Three Kings Day** — order by **December 16**

The full gift guide is up:

[**See the gift guide →**](https://primosmaternos.com/gifts?utm_source=gmail&utm_medium=email&utm_campaign=holiday-2026&utm_content=1)

Eight SKUs, from a $57 gallery wrap to a $324 large rolled canvas, with five framed 24"×36" options in the middle at $214. The image comes from a digital archive of the Sacred Original, certified in Mexico in 1998 as a faithful reproduction, and both certifications ship with every order. You don't have to take that on trust: [we publish both certificates in full](https://primosmaternos.com/authenticity), alongside crops of the face, the stars and the weave cut from the actual print file at full size. Canvases are printed in the USA on archival stock. Free U.S. shipping, 30 days to return.

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$holiday-2$tpl$, $tpl$Retail · Email 2 — Gift-guide push, before the deadline$tpl$, $tpl$Retail$tpl$, 2,
  $tpl$For the person who already has "everything Guadalupe"$tpl$,
  $tpl$Three price bands, six recipients, one image. Four days left to order for the feast.$tpl$,
  $tpl$Dear @firstname,

No discount code. No manufactured panic. Just a real deadline: November 20.

Just this: the image comes from a digital archive of the Sacred Original, certified in Mexico in 1998 as a faithful reproduction, and [both certificates are published in full](https://primosmaternos.com/authenticity). The canvas is printed in the USA on archival stock at 287.5 pixels per inch, and it lasts. The 24"×36" framed at $214 is the piece most people give — ready to hang the moment it's unwrapped, five frame styles to match the recipient's home.

Not sure which size? The [size guide](https://primosmaternos.com/canvas-sizes) gives the viewing distance and hanging height for each one, which is usually what settles it.

Some ideas for who to give it to:

- Grandparents or parents with roots in Mexico or Latin America
- A newlywed couple's first apartment (the $57 gallery wrap fits any wall)
- A godchild at confirmation
- A pastor's rectory or a religious sister's cell
- The family member who hosts the Dec 12 celebration every year

[**Pick a canvas →**](https://primosmaternos.com/gifts?utm_source=gmail&utm_medium=email&utm_campaign=holiday-2026&utm_content=2)

Order by Nov 20 for December 12 delivery.

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$holiday-3$tpl$, $tpl$Retail · Email 3 — Novena reminder$tpl$, $tpl$Retail$tpl$, 3,
  $tpl$The Novena starts tomorrow$tpl$,
  $tpl$Nine days of prayer for the four apparitions, leading into the December 12 feast. A short read on the story if you're new to it.$tpl$,
  $tpl$Dear @firstname,

Tomorrow — Thursday, December 3 — the traditional Novena to Our Lady of Guadalupe begins. Nine days of prayer, one for each of the four apparitions to Juan Diego and the one to Juan Bernardino, leading into the feast day on December 12.

If you'd like a short read on the apparition itself — what actually happened at Tepeyac in 1531, what the roses on the frozen hilltop meant — we published a piece on the site:

[**Read: The Sign on the Tilma →**](https://primosmaternos.com/blog/apparition?utm_source=gmail&utm_medium=email&utm_campaign=holiday-2026&utm_content=3a)

A canvas ordered now will not reach you before the feast, but it will arrive well inside the Jubilee year, and there is still time for Christmas if you order by Friday, December 4:

[**See the gift guide →**](https://primosmaternos.com/gifts?utm_source=gmail&utm_medium=email&utm_campaign=holiday-2026&utm_content=3b)

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$holiday-4$tpl$, $tpl$Retail · Email 4 — Last call for Christmas$tpl$, $tpl$Retail$tpl$, 4,
  $tpl$Last call for Christmas delivery$tpl$,
  $tpl$December 4 is the last order date for Christmas.$tpl$,
  $tpl$Dear @firstname,

Short one.

December 12 has passed as an order date: a canvas ordered now cannot be printed, framed and carried to you before the feast on Saturday, December 12, and we would rather say so than take the order and disappoint you.

**Christmas is still open, but today is the last day. Order by tomorrow, Friday, December 4,** and a canvas gets there. After that, Three Kings Day on January 6, with December 16 as the last order date.

The Jubilee Year for Our Lady of Guadalupe that opened in Mexico City on October 12 runs a full year — through October 12, 2027. If the canvas doesn't get to you before December 12, it still lands in the middle of a Jubilee year of grace.

[**Order for Christmas →**](https://primosmaternos.com/gifts?utm_source=gmail&utm_medium=email&utm_campaign=holiday-2026&utm_content=4)

Christmas order deadline is December 4. For Three Kings Day on January 6, order by December 16.

Thanks and a blessed Advent to you.

Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-1$tpl$, $tpl$Novena · Dec 2 — Launch email (day before Novena begins)$tpl$, $tpl$Novena$tpl$, 1,
  $tpl$The Novena to Our Lady of Guadalupe starts tomorrow$tpl$,
  $tpl$Nine days of prayer, one per apparition. Delivered to your inbox each morning at 6 AM Eastern.$tpl$,
  $tpl$Dear @firstname,

The traditional Novena to Our Lady of Guadalupe begins tomorrow, Wednesday, December 3. It runs nine days into the feast on December 12 — one day of prayer for each of Our Lady's four apparitions to Saint Juan Diego and the fifth to his uncle Juan Bernardino.

If you would like to pray it with us, we will send one short email each morning at 6 AM Eastern, December 3–11. Each email contains that day's meditation, the words spoken to Juan Diego, four Hail Marys, and the Memorare to Our Lady of Guadalupe.

If you prefer to pray at your own pace, the full text of the Novena is on the site — free to read, print, or share:

[**The full Novena, all nine days →**](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=launch)

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-2$tpl$, $tpl$Novena · Dec 3 — Day 1 · The first apparition$tpl$, $tpl$Novena$tpl$, 2,
  $tpl$Day 1 of the Novena — the first apparition$tpl$,
  $tpl$"Know that I am the Virgin Mary, Mother of the true God…"$tpl$,
  $tpl$Dear @firstname,

**Day 1 · December 3, 1531 at Tepeyac**

On that Saturday morning, Mary spoke to Juan Diego for the first time:

> *"My dear son, whom I love tenderly, know that I am the Virgin Mary, Mother of the true God, Giver and Maintainer of life, Creator of all things, Lord of heaven and earth, Who is in all places. I wish a temple to be erected here where I can manifest the compassion I have for the natives and for all who solicit my help."*

Your words, heavenly Mother, fill my heart with love and gratitude. I turn to you today confident of obtaining through your intercession the grace which will enable me to live in accordance with the teaching of your Divine Son. Do not abandon me in this vale of tears. Have compassion on my anxieties and cares.

Pray four Hail Marys — one for each apparition — and the Memorare.

[Full text of today's meditation and the Memorare →](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=day-1#day-1)

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-3$tpl$, $tpl$Novena · Dec 4 — Day 2 · The words that anchor us$tpl$, $tpl$Novena$tpl$, 3,
  $tpl$Day 2 — "Am I not here who am your Mother?"$tpl$,
  $tpl$The words spoken on Mary's fourth visit to Juan Diego.$tpl$,
  $tpl$Dear @firstname,

**Day 2 · The fourth apparition**

On her fourth visit, Mary said to Juan Diego:

> *"Do not let anything afflict you, and do not be afraid of any illness or accident or pain. Am I not here who am your Mother? Are you not under my shadow and protection? Is there anything else that you need?"*

Turn then, most gracious Mother, your eyes of mercy towards me today. Make it possible for me to put all my troubles and worries at your feet. I know you will remember you are my Mother, and I am under your shadow and protection.

Four Hail Marys. The Memorare.

[Today's meditation →](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=day-2#day-2)

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-4$tpl$, $tpl$Novena · Dec 5 — Day 3 · Juan Bernardino's healing$tpl$, $tpl$Novena$tpl$, 4,
  $tpl$Day 3 — "Immaculate Virgin Mary who crushed the Serpent"$tpl$,
  $tpl$The name Mary gave to Juan Diego's dying uncle.$tpl$,
  $tpl$Dear @firstname,

**Day 3 · The apparition to Juan Bernardino**

Juan Diego's uncle, Juan Bernardino, was near death. Mary appeared to him, cured him, and gave him her name — the name that told the Aztecs that their season of human sacrifice was ending:

> *"Immaculate Virgin Mary who crushed the Serpent."*

Hail Holy Queen, merciful Mother. Hail our life, our sweetness and our hope. Pray for us today. Exterminate the Serpent of Evil from our lives so we may be made worthy of the promises of Christ, your Divine Son.

Four Hail Marys. The Memorare.

[Today's meditation →](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=day-3#day-3)

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-5$tpl$, $tpl$Novena · Dec 6 — Day 4 · The image as written message$tpl$, $tpl$Novena$tpl$, 5,
  $tpl$Day 4 — the image itself preaches$tpl$,
  $tpl$Every detail of the tilma told the Aztecs something specific.$tpl$,
  $tpl$Dear @firstname,

**Day 4 · The image as picture writing**

To an Aztec looking at the tilma in 1531, the image was a codex. Your regal figure in human form told them that your dwelling place had once been on earth. The rays of the sun, the clouds around your body, the stars on your garment, the crescent under your feet, the angel — all of them said: my home is now in heaven, and the human soul is immortal.

O Holy Mary, let the same image teach me never to forget the immortality of my soul, that Heaven is my goal and my inheritance. Amid the temptations of this life, let me think always of that home of peace and eternal bliss.

Four Hail Marys. The Memorare.

[Today's meditation →](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=day-4#day-4)

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-6$tpl$, $tpl$Novena · Dec 7 — Day 5 · The rays of the sun$tpl$, $tpl$Novena$tpl$, 6,
  $tpl$Day 5 — eclipsing the sun-god$tpl$,
  $tpl$The Aztecs sacrificed thousands to the Sun. Then the tilma stood in front of it.$tpl$,
  $tpl$Dear @firstname,

**Day 5 · The rays of the sun**

For centuries the natives of Mexico worshipped the Sun. Countless human beings were sacrificed in its honor. When the Indians beheld the Image on the tilma — with her figure eclipsing the sun so that only its rays are visible — they understood the lesson.

O Holy Mary, through the mystery of the Incarnation of your Son, obtain for us the light to understand the greatness of the benefit he has bestowed upon us in becoming our Brother and in giving you, his own Mother, to be our Mother also.

Four Hail Marys. The Memorare.

[Today's meditation →](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=day-5#day-5)

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-7$tpl$, $tpl$Novena · Dec 8 — Day 6 · The stars on the mantle$tpl$, $tpl$Novena$tpl$, 7,
  $tpl$Day 6 — the stars themselves testify$tpl$,
  $tpl$The stars on her mantle told the Aztecs their gods weren't gods.$tpl$,
  $tpl$Dear @firstname,

**Day 6 · The stars on the mantle**

The fires that had burned on the altars of the false gods were extinguished forever after the Indians contemplated the Image and saw her attired with the firmament, covered with stars. The stars had been made by the Invisible God to serve mankind — they could not themselves be deities to whom sacrifice was due.

Most Holy Mary, through the image stamped by God on the Indian's garment, you have brought millions of pagans into the light of the true faith. Obtain for me the grace of understanding the message it contains. Shed upon me the light of your countenance; direct and sanctify all my undertakings today.

Four Hail Marys. The Memorare.

[Today's meditation →](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=day-6#day-6)

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-8$tpl$, $tpl$Novena · Dec 9 — Day 7 · The cross at her throat$tpl$, $tpl$Novena$tpl$, 8,
  $tpl$Day 7 — the small cross that opened the way$tpl$,
  $tpl$The same cross was on Cortés' banner. The Aztecs recognized it.$tpl$,
  $tpl$Dear @firstname,

**Day 7 · The cross of our redemption**

At her throat, the tilma bears a small black cross on a gold brooch. It was the same cross the Aztecs had seen on the banner of Hernando Cortés. When they saw it on her image, they went to the Spanish missionaries eager to know its meaning — and were told of the Savior who came from heaven to redeem the human race, and of the Virgin Mother of that Savior.

Holy Virgin, Mary of Guadalupe, my Queen and Mother, inspire us to see in this miraculous picture the instrument of conversion, you who are the adorable Queen and Mother of the Apostles and Missionaries.

Four Hail Marys. The Memorare.

[Today's meditation →](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=day-7#day-7)

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-9$tpl$, $tpl$Novena · Dec 10 — Day 8 · The roses at Tepeyac$tpl$, $tpl$Novena$tpl$, 9,
  $tpl$Day 8 — "You are my ambassador worthy of confidence"$tpl$,
  $tpl$The last words Juan Diego heard from her lips.$tpl$,
  $tpl$Dear @firstname,

**Day 8 · The roses**

Juan Diego cut the roses blooming on the frozen hilltop and brought them down. Mary arranged them in his tilma with her own hands and tied it around his neck. The last words he heard from her:

> *"You are my ambassador worthy of confidence. Go in peace."*

The picture on that coarse cloth could not have been painted by human hands. It convinced the bishop, as it ought to convince every person who looks at it, that Juan Diego's message was truly hers.

Humbly, my Queen and Mother, let me be your ambassador like Juan Diego today — to give the doctrine contained in your Image to my friends, believers and unbelievers alike.

Four Hail Marys. The Memorare.

[Today's meditation →](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=day-8#day-8)

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-10$tpl$, $tpl$Novena · Dec 11 — Day 9 · The conversion of a nation$tpl$, $tpl$Novena$tpl$, 10,
  $tpl$Day 9 — nine million baptisms in ten years$tpl$,
  $tpl$The last day of the Novena, the day before the feast.$tpl$,
  $tpl$Dear @firstname,

**Day 9 · The conversion of a nation**

O Holy Virgin, enthroned on the spot you chose in the very heart of an idolatrous nation, you worked its conversion. After seeing the Image on the tilma of their countryman, the Indians stripped their temples of idols. They built churches on whose towers gleaming crosses shone in the sun. The huge drum that had innumerable times announced human sacrifice was heard no more.

As Juan Diego spent the remaining seventeen years of his life giving your spoken message to the Indians, so permit me, my loving Mother, to help in making known your celestial message among my countrymen. Animate and bless all who join in the Apostleship and Novena, having as their banner your admirable image on Juan Diego's tilma, together with the cross, emblem of our redemption.

Four Hail Marys. The Memorare.

[Today's meditation →](https://primosmaternos.com/novena?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=day-9#day-9)

Tomorrow is the feast. A blessed vigil to you.

Peace Bill$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$novena-11$tpl$, $tpl$Novena · Dec 12 — Feast day$tpl$, $tpl$Novena$tpl$, 11,
  $tpl$Today is the feast of Our Lady of Guadalupe$tpl$,
  $tpl$Nine days of preparation. One day of the feast. Blessed December 12 to you and your family.$tpl$,
  $tpl$Dear @firstname,

Today is December 12 — the feast of Our Lady of Guadalupe.

Nine days into it we have prayed together. Today the Basilica in Mexico City receives more than three million pilgrims. Our Lady's Jubilee Year that Pope Leo XIV opened on October 12 continues through October 12, 2027.

Wherever you are, a blessed feast day to you and to your family. The Novena has ended; the year of Jubilee is only two months old.

If you would like a short piece on the events of December 12, 1531 that this feast commemorates:

[The Sign on the Tilma — Juan Diego's story →](https://primosmaternos.com/blog/apparition?utm_source=gmail&utm_medium=email&utm_campaign=novena-2026&utm_content=feast)

Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO mail_templates (slug, name, segment, position, subject, preview, body) VALUES (
  $tpl$intl-1$tpl$, $tpl$International · Email 1 — Reply: buying from outside the US$tpl$, $tpl$International$tpl$, 1,
  $tpl$Ordering the Guadalupe canvas from outside the US$tpl$,
  $tpl$Our canvases are on eBay, which ships internationally and handles customs.$tpl$,
  $tpl$Dear @firstname,

Thank you for your interest in our Our Lady of Guadalupe canvas. Our website checkout ships to the 50 U.S. states and Puerto Rico only, but the same canvases are listed on eBay, which ships internationally and handles customs and import charges at checkout.

- [24" × 36" rolled canvas](https://www.ebay.com/itm/184136879559)
- [36" × 54" rolled canvas](https://www.ebay.com/itm/184670577846)
- [24" × 36" gold frame](https://www.ebay.com/itm/184779375228)
- [24" × 36" cherry frame](https://www.ebay.com/itm/184779364948)
- [24" × 36" beaded mahogany frame](https://www.ebay.com/itm/184779363392)
- [24" × 36" black red oak frame](https://www.ebay.com/itm/184779367663)
- [24" × 36" silver ornate frame](https://www.ebay.com/itm/184779359135)

It is the same canvas we sell here: image created in Mexico from a scan of the original tilma, canvas printed in the USA, two Mexican certificates included.

If you have any questions or concerns, feel free to reach out to me.

Thanks,
Peace Bill

William F. Leonard
Saxon Enterprises, Inc. — dba Primos Maternos
15 Shea Ln, Tinton Falls, NJ 07724
wfleonard@primosmaternos.com · 732-673-4260$tpl$
) ON CONFLICT (slug) DO NOTHING;
